In [79]:
import sqlite3
import pandas as pd
import numpy as np
from IPython.display import display, HTML
#path = "C:/Users/jxx/AppData/Roaming/fpdb/database/fpdb.db3"
path = "/Users/xxx/.fpdb/database/fpdb.db3"
con = sqlite3.connect(path)

cur = con.cursor()

cur.execute("""SELECT name FROM sqlite_master
            WHERE type='table'
            ORDER BY name;""")

result = cur.fetchall()

print(result)

[('Actions',), ('Autorates',), ('Backings',), ('Boards',), ('CardsCache',), ('Files',), ('Gametypes',), ('Hands',), ('HandsActions',), ('HandsPlayers',), ('HandsPots',), ('HandsStove',), ('HudCache',), ('Months',), ('Players',), ('PositionsCache',), ('Rank',), ('RawHands',), ('RawTourneys',), ('Sessions',), ('SessionsCache',), ('Settings',), ('Sites',), ('StartCards',), ('TourneyTypes',), ('Tourneys',), ('TourneysCache',), ('TourneysPlayers',), ('Weeks',), ('sqlite_stat1',)]

In [81]:
cur.execute("""SELECT * FROM Tourneys limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()


df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [82]:
cur.execute("""SELECT * FROM Actions limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [83]:
cur.execute("""SELECT * FROM Autorates limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [84]:
cur.execute("""SELECT * FROM Boards limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [85]:
cur.execute("""SELECT * FROM CardsCache limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [114]:
cur.execute("""SELECT * FROM Files where errs<>0""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [87]:
cur.execute("""SELECT * FROM Gametypes limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [88]:
cur.execute("""SELECT * FROM Hands limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [89]:
cur.execute("""SELECT * FROM HandsActions limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [90]:
cur.execute("""SELECT * FROM HandsPlayers limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [91]:
cur.execute("""SELECT * FROM HandsPots limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [92]:
cur.execute("""SELECT * FROM HandsStove limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [93]:

cur.execute("""SELECT * FROM HudCache limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [94]:
cur.execute("""SELECT * FROM Months limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [95]:

cur.execute("""SELECT * FROM Players limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [96]:
cur.execute("""SELECT * FROM PositionsCache limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [97]:
cur.execute("""SELECT * FROM Rank limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [98]:
cur.execute("""SELECT * FROM RawHands limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [99]:

cur.execute("""SELECT * FROM RawTourneys limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [100]:
cur.execute("""SELECT * FROM Sessions limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [101]:

cur.execute("""SELECT * FROM SessionsCache limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [102]:
cur.execute("""SELECT * FROM Settings limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [103]:

cur.execute("""SELECT * FROM Sites limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [104]:

cur.execute("""SELECT * FROM StartCards limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [105]:

cur.execute("""SELECT * FROM TourneyTypes limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [106]:
cur.execute("""SELECT * FROM Tourneys limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [107]:
cur.execute("""SELECT * FROM TourneysCache limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [108]:

cur.execute("""SELECT * FROM TourneysPlayers limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))

In [109]:
cur.execute("""SELECT * FROM Weeks limit 5""")
names = list(map(lambda x: x[0], cur.description))
result = cur.fetchall()
df = pd.DataFrame(result, columns=names)

display(HTML(df.to_html()))